{% set name = "PyLD" %}
{% set version = "2.0.1" %}
{% set sha256 = "6a309873e536bab413fa60c8186ba6329dbcc200eaf1ae3768d832532355d789" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - requests

  run:
    - python
    - requests

test:
  imports:
    - {{ name|lower }}
    - {{ name|lower }}.documentloader

about:
  home: https://pypi.python.org/pypi/{{ name }}/{{ version }}
  license: BSD-3-Clause
  summary: Python implementation of the JSON-LD API
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/digitalbazaar/{{ name|lower }}

extra:
  recipe-maintainers:
    - notestaff
