{% set name = "PyLD" %}
{% set version = "1.0.3" %}
{% set sha256 = "f50a08fc9be794e869f20e594311e6569be30bd3e3adc87a3f130cd9ba79228a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pyld
    - pyld.documentloader
    
about:
  home: https://pypi.python.org/pypi/PyLD/{{ version }}
  license: BSD-3-Clause
  summary: 'Python implementation of the JSON-LD API'
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/digitalbazaar/pyld

extra:
  recipe-maintainers:
    - notestaff
