{% set version = "3.0.0" %}

package:
  name: pyld
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/P/PyLD/pyld-{{ version }}.tar.gz
  sha256: b1913a06054f35a31e4d9916d184852909b2a3c5fea55c341bd00917cf8b22ef

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cachetools
    - frozendict
    - lxml
    - python >={{ python_min }}
    - requests

test:
  requires:
    - pip
    - aiohttp
    - python {{ python_min }}
  imports:
    - c14n
    - pyld
    - pyld.documentloader
    - pyld.documentloader.requests
    - pyld.documentloader.aiohttp
  commands:
    - pip check

about:
  home: https://github.com/digitalbazaar/pyld
  license: BSD-3-Clause
  summary: Python implementation of the JSON-LD API
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - notestaff
    - bollwyvl
