{% set version = "2.0.4" %}

package:
  name: pyld
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyLD/PyLD-{{ version }}.tar.gz
  sha256: 311e350f0dbc964311c79c28e86f84e195a81d06fef5a6f6ac2a4f6391ceeacc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4

  run:
    - cachetools
    - frozendict
    - lxml
    - python >=3.4
    - requests

test:
  requires:
    - pip
    - aiohttp
  imports:
    - c14n
    - pyld
    - pyld.documentloader
    - pyld.documentloader.requests
    - pyld.documentloader.aiohttp
  commands:
    - python -m pip check

about:
  home: https://github.com/digitalbazaar/pyld
  license: BSD-3-Clause
  summary: Python implementation of the JSON-LD API
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - notestaff
    - bollwyvl
